os: Visual Studio 2013
install:
  - set PATH=C:\Program Files (x86)\MSBuild\12.0\Bin;%PATH%
configuration: Release
branches:
  only:
    - appveyor

build:
  project: NginR.sln       
  verbosity: minimal
